// Behavioral parity between the TS engine port and the already
// oracle-validated Python fast engine (see the plan doc's Phase 5).
// Fixtures are generated by scripts/generate_js_fixtures.py from real
// random games played through the Python engine -- regenerate with
// `make js-fixtures` from the repo root after any engine.py change.

import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import type { PieceType } from "../src/engine/constants.js";
import { applyMove } from "../src/engine/apply.js";
import { generateLegalMoves } from "../src/engine/moves.js";
import { GameState } from "../src/engine/state.js";
import type { FixtureMove, FixtureState } from "./fixtureUtils.js";
import { deserializeState, moveKey } from "./fixtureUtils.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = join(__dirname, "fixtures");

interface FixtureStep {
  state: FixtureState;
  legalMoves: FixtureMove[];
  appliedMoveIndex: number | null;
}

interface Fixture {
  enabledTypes: number[];
  steps: FixtureStep[];
}

function loadFixture(file: string): Fixture {
  return JSON.parse(readFileSync(join(FIXTURES_DIR, file), "utf-8")) as Fixture;
}

const fixtureFiles = readdirSync(FIXTURES_DIR).filter(
  (f) => f.endsWith(".json") && f !== "encode_fixtures.json",
);
if (fixtureFiles.length === 0) {
  throw new Error(
    "no fixtures in js/test/fixtures -- run `make js-fixtures` from the repo root first",
  );
}

describe("engine parity: legal move generation matches the Python engine", () => {
  for (const file of fixtureFiles) {
    it(file, () => {
      const fixture = loadFixture(file);
      for (const [i, step] of fixture.steps.entries()) {
        const state = deserializeState(step.state);
        const actualKeys = new Set(generateLegalMoves(state).map(moveKey));
        const expectedKeys = new Set(step.legalMoves.map(moveKey));
        expect(actualKeys, `${file} step ${i}`).toEqual(expectedKeys);
      }
    });
  }
});

describe("engine parity: full game replay via applyMove matches the Python engine", () => {
  for (const file of fixtureFiles) {
    it(file, () => {
      const fixture = loadFixture(file);
      const enabledTypes = new Set(fixture.enabledTypes as PieceType[]);
      const state = GameState.newGame(enabledTypes);

      for (let i = 0; i < fixture.steps.length - 1; i++) {
        const step = fixture.steps[i];
        if (step.appliedMoveIndex === null) break;
        const appliedFixtureMove = step.legalMoves[step.appliedMoveIndex];

        const legal = generateLegalMoves(state);
        const match = legal.find((m) => moveKey(m) === moveKey(appliedFixtureMove));
        expect(match, `${file} step ${i}: applied move not found in TS legal moves`).toBeDefined();
        applyMove(state, match!);

        const next = fixture.steps[i + 1].state;
        expect(state.currentPlayer, `${file} step ${i} currentPlayer`).toBe(next.currentPlayer);
        expect(state.turnNo, `${file} step ${i} turnNo`).toBe(next.turnNo);
        expect(state.ply, `${file} step ${i} ply`).toBe(next.ply);
        expect(state.gameOver, `${file} step ${i} gameOver`).toBe(next.gameOver);
        expect(state.winner, `${file} step ${i} winner`).toBe(next.winner);

        const actualBoard: Record<string, number[]> = {};
        for (const [k, v] of state.board) actualBoard[k] = v;
        expect(actualBoard, `${file} step ${i} board`).toEqual(next.board);
      }
    });
  }
});
