// Shared helpers for reading fixtures generated by
// scripts/generate_js_fixtures.py and reconstructing a GameState from one.

import type { PieceType } from "../src/engine/constants.js";
import { GameState } from "../src/engine/state.js";
import type { Owner, Piece, Pos } from "../src/engine/state.js";

export interface FixtureMove {
  kind: number;
  pieceId: number;
  to: [number, number, number];
  thrownPieceId: number | null;
}

export interface FixtureState {
  pieces: { id: number; pieceType: number; owner: Owner }[];
  board: Record<string, number[]>;
  position: Record<string, [number, number, number] | null>;
  hand: [number[], number[]];
  queenPlaced: [boolean, boolean];
  currentPlayer: Owner;
  turnNo: number;
  ply: number;
  lastMovedPieceId: number | null;
  lastMovedPly: number | null;
  gameOver: boolean;
  winner: number | null;
}

export function deserializeState(fs: FixtureState): GameState {
  const pieces = new Map<number, Piece>();
  for (const p of fs.pieces) {
    pieces.set(p.id, { id: p.id, pieceType: p.pieceType as PieceType, owner: p.owner });
  }
  const board = new Map<string, number[]>();
  for (const [key, stack] of Object.entries(fs.board)) board.set(key, [...stack]);
  const position = new Map<number, Pos | null>();
  for (const [pidStr, pos] of Object.entries(fs.position)) {
    position.set(Number(pidStr), pos ? [pos[0], pos[1], pos[2]] : null);
  }
  const hand: [number[], number[]] = [[...fs.hand[0]], [...fs.hand[1]]];
  const state = new GameState(
    pieces,
    board,
    position,
    hand,
    [fs.queenPlaced[0], fs.queenPlaced[1]],
    fs.currentPlayer,
    fs.turnNo,
    fs.ply,
  );
  state.lastMovedPieceId = fs.lastMovedPieceId;
  state.lastMovedPly = fs.lastMovedPly;
  state.gameOver = fs.gameOver;
  state.winner = fs.winner;
  return state;
}

export function moveKey(m: {
  kind: number;
  pieceId: number;
  to: readonly number[];
  thrownPieceId?: number | null;
}): string {
  return `${m.kind}:${m.pieceId}:${m.to[0]},${m.to[1]},${m.to[2]}:${m.thrownPieceId ?? "-"}`;
}
